from __future__ import annotations

from typing import Protocol

from spacemaker.domain.gallery_index import FileStat
from spacemaker.domain.library import LibraryFolder


class FileSystemPort(Protocol):
	def ensure_library_folders(self, library_root: str) -> None: ...

	def file_size(self, path: str) -> int: ...

	def file_stat(self, path: str) -> FileStat: ...

	def exists(self, path: str) -> bool: ...

	def move_file(self, source: str, destination: str) -> None: ...

	def copy_file(self, source: str, destination: str) -> None: ...

	def ensure_parent_directory(self, file_path: str) -> None: ...

	def delete_file(self, path: str) -> None: ...

	def list_files_recursive(self, folder: str) -> list[str]: ...

	def list_files_in_library_folder(self, library_root: str, folder: LibraryFolder) -> list[str]: ...

	def count_files_in_folder(self, library_root: str, folder: LibraryFolder) -> int: ...

	def library_path(self, library_root: str, folder: LibraryFolder, relative: str) -> str: ...
