from __future__ import annotations

from typing import Literal, Protocol

from spacemaker.domain.gallery import GalleryItem
from spacemaker.domain.gallery_index import FileStat, GalleryCursor, GalleryIndexRow, GalleryPage


class GalleryIndexPort(Protocol):
	def snapshot_stats(self, library_root: str) -> dict[str, FileStat]: ...

	def apply_sync(self, library_root: str, *, upserts: list[GalleryIndexRow], removed: list[str]) -> None: ...

	def remove(self, library_root: str, relative_path: str) -> None: ...

	def get(self, library_root: str, relative_path: str) -> GalleryIndexRow | None: ...

	def page(self, library_root: str, *, cursor: GalleryCursor | None, limit: int) -> GalleryPage: ...

	def days_with_media(self, library_root: str, year: int, month: int) -> list[int]: ...

	def items_for_day(self, library_root: str, year: int, month: int, day: int) -> list[GalleryItem]: ...

	def neighbor(
		self, library_root: str, relative_path: str, *, direction: Literal["prev", "next"]
	) -> GalleryItem | None: ...

	def count(self, library_root: str) -> int: ...
