from __future__ import annotations

from typing import Literal, Protocol

from spacemaker.domain.gallery import GalleryItem
from spacemaker.domain.gallery_index import FileStat, GalleryCursor, GalleryIndexRow, GalleryPage


class GalleryIndexPort(Protocol):
	async def snapshot_stats(self, library_root: str) -> dict[str, FileStat]: ...

	async def apply_sync(self, library_root: str, *, upserts: list[GalleryIndexRow], removed: list[str]) -> None: ...

	async def remove(self, library_root: str, relative_path: str) -> None: ...

	async def get(self, library_root: str, relative_path: str) -> GalleryIndexRow | None: ...

	async def page(self, library_root: str, *, cursor: GalleryCursor | None, limit: int) -> GalleryPage: ...

	async def days_with_media(self, library_root: str, year: int, month: int) -> list[int]: ...

	async def items_for_day(self, library_root: str, year: int, month: int, day: int) -> list[GalleryItem]: ...

	async def neighbor(
		self, library_root: str, relative_path: str, *, direction: Literal["prev", "next"]
	) -> GalleryItem | None: ...

	async def count(self, library_root: str) -> int: ...

	async def close(self, library_root: str) -> None: ...
